### Get All Boards
GET http://localhost:8081/boards
Accept: application/json

### Create New Board
POST http://localhost:8081/boards
Content-Type: application/json
Accept: application/json

{
  "name": "Surfboard",
  "description": "Used to navigate the internet"
}

### Add New Task to Board

@boardId = 9d820a52-6ddc-4933-a6d2-ceb4aae3f49a
POST http://localhost:8081/boards/{{boardId}}/tasks
Content-Type: application/json
Accept: application/json

{
  "name": "Task-Force Unicorn",
  "description": "Has only one corn",
  "userId": "{{boardId}}"
}

### Delete Task from Board

@taskId = 4e1ca5b6-ff89-4899-b33a-ece4877a9d64
DELETE http://localhost:8081/tasks/{{taskId}}
Accept: application/json